version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nc6cj69kr6kl"
s3_prefix = "sam-app"
region = "us-east-1"
profile = "lonny-cs"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
